name: teachmate_pro
description: "AI-powered teaching assistant platform"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_generative_ai: ^0.4.6
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  flutter_localizations:
    sdk: flutter
  printing: ^5.13.3
  pdf: ^3.11.1
  path_provider: ^2.1.4
  share_plus: ^10.1.1
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  syncfusion_flutter_calendar: ^27.1.56
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  animations: ^2.0.11
  flutter_dotenv:
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
